name: release-main

on:
  release:
    types: [published]
    branches: [main]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read


jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      
      - name: Publish to Pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          source .venv/bin/activate
          make publish


